export default [
  {
    title: 'Admin Dashboard',
    route: 'dashboard',
    icon: 'tachometer-alt',
    pack: 'fas',
    auth: 'admin',
  },
  {
    title: 'Admins',
    route: 'admin.list',
    icon: 'users',
    pack: 'fas',
    permissions: ['Admin List', 'Admin List Owner'],
    auth: 'admin',
  },
  // {
  //   title: 'Roles',
  //   route: 'role.list',
  //   icon: 'user-lock',
  //   pack: 'fas',
  //   role: 'SupperAdmin',
  //   auth: 'admin',
  // },
  {
    title: 'Teachers',
    route: 'teacher.list',
    icon: 'user-graduate',
    pack: 'fas',
    permissions: ['Teacher List', 'Teacher List Owner'],
    auth: 'admin',
  },
  {
    title: 'Students',
    route: 'student.list',
    icon: 'user-graduate',
    pack: 'fas',
    permissions: ['Student List', 'Student List Owner'],
    auth: 'admin',
  },
  {
    title: 'ClassLevels', route: 'class_level.list', icon: 'layer-group', pack: 'fas', permissions: ['ClassLevel List', 'ClassLevel List Owner'], auth: 'admin',
  },
  {
    title: 'Programs', route: 'program.list', icon: 'calendar-alt', pack: 'fas', permissions: ['Programs List', 'Programs List Owner'], auth: 'admin',
  },
  {
    title: 'Fees', route: 'fee.list', icon: 'money-check-alt', pack: 'fas', permissions: ['Fee List', 'Fee List Owner'], auth: 'admin',
  },
  {
    title: 'Years', route: 'year.list', icon: 'calendar-plus', pack: 'far', permissions: ['Year List', 'Year List Owner'], auth: 'admin',
  },
  {
    title: 'Notifications', route: 'notification.list', icon: 'bell', pack: 'fas', permissions: ['Notification List', 'Notification List Owner'], auth: 'admin',
  },
  {
    title: 'Posts',
    route: 'post.list',
    icon: 'newspaper',
    pack: 'fas',
    permissions: ['Post List', 'Post List Owner'],
    auth: 'admin',
  },
  {
    title: 'Pages',
    route: 'page.list',
    icon: 'file-alt',
    pack: 'fas',
    permissions: ['Page List', 'Page List Owner'],
    auth: 'admin',
  },
  {
    title: 'Tags',
    route: 'tag.list',
    icon: 'tags',
    pack: 'fas',
    permissions: ['Tag List', 'Tag List Owner'],
    auth: 'admin',
  },
  {
    title: 'Menus',
    route: 'menu.list',
    icon: 'ellipsis-h',
    pack: 'fas',
    permissions: ['Menu List', 'Menu List Owner'],
    auth: 'admin',
  },
  // {
  //     title: 'Setting',
  //     route: 'settings',
  //     icon: 'cogs',
  //     pack: 'fas',
  //     role: 'SupperAdmin',
  // },
  // {
  //     title: 'Generate Settings',
  //     route: 'setting.list',
  //     icon: 'cogs',
  //     pack: 'fas',
  //     role: 'SupperAdmin',
  // },
]
